### ISSUE TITLE
Force update does not really force an update.

### ISSUE THREAD

**Issue by praharshbhatt** [ofload/native_updater#15]
Users can easily dismiss the dialog box.
Now since this is a native window, you may not have the ability to change the UI.
Although be any chance is it possible to notify the user's choice by a callback?

**Comment by milhomem** [comment]
Hi @praharshbhatt it should close the app in any case, but of course this relies on the Flutter implementation for that platform.

dismissable should have a callback to close the app.

would you mind sharing more information and how to reproduce the issue?
