### ISSUE TITLE
No implementation found for method checkForUpdate on channel in_app_update

### ISSUE THREAD

**Issue by olintosergio** [ofload/native_updater#17]
**No implementation found for method checkForUpdate on channel in_app_update**
I'm getting the error above, does anyone know how to fix it? Thanks

**Comment by milhomem** [comment]
Hi @olintosergio 

Can you please share more information?

At minimum the version of this project you’re using, the platform the error occurs iOS or Android, the version of the platform, a sample snippet of the source code, any additional details you think could help.

There’s a new version of this project, please try to update first.

**Comment by milhomem** [comment]
Closed as Stale.
