### ISSUE TITLE
how get http statusCode?

### ISSUE THREAD

**Issue by marleynoleto** [ofload/native_updater#18]
Hi, in example you describe that I need to get http status code by a requisition. You would send us a example? Or send to us a link thet document this process?

`/// For example: You got status code of 412 from the
    /// response of HTTP request.
    /// Let's say the statusCode 412 requires you to force update
    int statusCode = 412;
`

thanks

**Comment by milhomem** [comment]
Hi @marleynoleto this is just an hypothetical case if you are using the http library to request your API. In this example you could look for status codes to control the update of the App remotely.

We use DIO and the Interceptors functionality to monitor all http requests and look for the http status code.

You can use any logic to trigger this module. Please let me know if you need a complete example and I can add one to the examples folder.

**Comment by Sakib0604** [comment]
Hi @milhomem can you give a complete example how to implement this in flutter project?

Thanks

**Comment by milhomem** [comment]
Hi @marleynoleto @Sakib0604 , I will work on that and add a complete example with Dio.

**Comment by sebastianbuechler** [comment]
Would also be interested in your example with Dio. Thanks!

**Comment by milhomem** [comment]
Hi @marleynoleto @sebastianbuechler @Sakib0604 

I hope this simple example in [dede4df](https://github.com/ofload/native_updater/commit/dede4dfee75c445f8e5aa17ab3933e3027469c64) will help you. Let me know if you guys any question.

I've simply followed https://pub.dev/packages/dio#handling-errors guide.

Best,
