### ISSUE TITLE
Dialog not shown when App on Playstore

### ISSUE THREAD

**Issue by SyedAmmarSohail** [ofload/native_updater#21]
I'm very appreciate your work for in app update.
But one thing I notice that update dialog not shown when an app is already on play store even the version number and code is  different. 
I used latest native_updater version 0.1.0
Please look into this.

**Comment by milhomem** [comment]
Hi @SyedAmmarSohail , I'm not quite sure what you mean but this module does not detect new versions on the store automatically. All logic is up to the developer.

You can check your current version with `PackageInfo`:
```
 /// Get Current installed version of app    
final PackageInfo info = await PackageInfo.fromPlatform();    
String currentVersion = info.version.trim().replaceAll("[a-zA-Z]|-", "");
```

If you want something that compares automatically with the stores you should look at something like https://pub.dev/packages/new_version
