### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by elnurxf** [ofload/native_updater#25]
_CastError: Null check operator used on a null value
  File "native_updater.dart", line 79, in NativeUpdater._showCupertinoAlertDialog
  File "native_updater.dart", line 58, in NativeUpdater.displayUpdateAlert

**Comment by Sylvain17** [comment]
In fact you have to add 
```
NativeUpdater.displayUpdateAlert(
  context,
  forceUpdate: true,
  appStoreUrl: '<Your App Store URL>', // <== THIS LINE
);

```
to avoid this error.

**Comment by elnurxf** [comment]
Did this way. I thought package gets store URL automatically depending on app namespace.

Thank you.
