### ISSUE TITLE
Support for the iOS?

### ISSUE THREAD

**Issue by TharaniP** [ofload/native_updater#27]
Hi,

Can we use this package for the ios platform as well? 

Thanks for the help in advance.

**Comment by Sylvain17** [comment]
Yes you can. The "iOS" label is missing, but it can be used for iOS

**Comment by milhomem** [comment]
Hi @TharaniP , yes you can, there's a new version out now with more flexibility for the labels. Let me know if it works for you.

Tks @Sylvain17 for answering.
